### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hex13** [hex13/enter-ghost#2]
- [ ] decoupling npm modules from repo
- [ ] git diffs (should be optimized )
- [ ] tab menu (hamburger): close tab, change view mode etc.
- [ ] search in project
- [ ] files other than *.js (for example HTML, CSS)
- [ ] tab pinning
- [ ] control by keyboard only
- [ ] creating new files, renaming files etc.

linting:
- [ ] by opinionated ESLint configuration
- [ ] custom linting (by taking ESLint configuration from project itself)

Mouse support:
- [ ] drag'n'drop features (e.g. moving tabs)
- [ ] resize windows

JS code intelligence
- [ ] scopeAt(cursor)
- [ ] definitions 
- [ ]  highlight variable references at cursor

refactoring
- [ ] extract to new file
